#!/bin/bash

# build mathjax.html
tex_cmds=$(cat \
    LaTeX/basics/macros.tex \
    LaTeX/basics/mathjax.tex \
) || exit 1
output_html=LaTeX/mathjax.html

cat <<- EOF > "$output_html"
	<!-- mathjax for local use -->

	<div class="mathjax_macros" style="display: none;">
	\$ $tex_cmds \$
	</div>
EOF

git add --intent-to-add "$output_html"

if ! git diff --exit-code "$output_html"; then
    git add "$output_html"
    exit 1
fi
